export const ROLES = Object.freeze({
  OWNER: "owner",
  ADMIN: "admin",
  TEAM_MEMBER: "team_member",
  TEAM_LEADER: "team_leader",
  MANAGER: "manager",
  HR: "hr",
});

export const PERMISSIONS = Object.freeze({
  EMPLOYEE_READ_SELF: "employee:read:self",
  EMPLOYEE_READ_TEAM: "employee:read:team",
  EMPLOYEE_READ_DEPARTMENT: "employee:read:department",
  EMPLOYEE_READ_COMPANY: "employee:read:company",
  EMPLOYEE_WRITE_COMPANY: "employee:write:company",
  LEAVE_CREATE_SELF: "leave:create:self",
  LEAVE_READ_SELF: "leave:read:self",
  LEAVE_READ_TEAM: "leave:read:team",
  LEAVE_READ_DEPARTMENT: "leave:read:department",
  LEAVE_READ_COMPANY: "leave:read:company",
  LEAVE_APPROVE_TEAM: "leave:approve:team",
  LEAVE_APPROVE_DEPARTMENT: "leave:approve:department",
  LEAVE_APPROVE_COMPANY: "leave:approve:company",
  LEAVE_POLICY_WRITE: "leave:policy:write",
  PAYROLL_READ_SELF: "payroll:read:self",
  PAYROLL_WRITE_COMPANY: "payroll:write:company",
  USER_PROVISION_COMPANY: "user:provision:company",
  AUDIT_READ_COMPANY: "audit:read:company",
  ATTENDANCE_CLOCK_SELF: "attendance:clock:self",
});

const ALL = Object.values(PERMISSIONS);

const MEMBER = [
  PERMISSIONS.EMPLOYEE_READ_SELF,
  PERMISSIONS.LEAVE_CREATE_SELF,
  PERMISSIONS.LEAVE_READ_SELF,
  PERMISSIONS.PAYROLL_READ_SELF,
  PERMISSIONS.ATTENDANCE_CLOCK_SELF,
];

const LEADER = [
  ...MEMBER,
  PERMISSIONS.EMPLOYEE_READ_TEAM,
  PERMISSIONS.LEAVE_READ_TEAM,
  PERMISSIONS.LEAVE_APPROVE_TEAM,
];

const MANAGER = [
  ...LEADER,
  PERMISSIONS.EMPLOYEE_READ_DEPARTMENT,
  PERMISSIONS.LEAVE_READ_DEPARTMENT,
  PERMISSIONS.LEAVE_APPROVE_DEPARTMENT,
];

// Company-wide People tab access (viewing and editing every employee's
// record) is reserved for HR — not the generic "Admin Access" role — plus
// the owner (who holds every permission via ALL below).
const ADMIN = [
  ...MANAGER,
  PERMISSIONS.LEAVE_READ_COMPANY,
  PERMISSIONS.LEAVE_APPROVE_COMPANY,
  PERMISSIONS.LEAVE_POLICY_WRITE,
  PERMISSIONS.PAYROLL_WRITE_COMPANY,
  PERMISSIONS.USER_PROVISION_COMPANY,
  PERMISSIONS.AUDIT_READ_COMPANY,
];

const HR = [
  ...ADMIN,
  PERMISSIONS.EMPLOYEE_READ_COMPANY,
  PERMISSIONS.EMPLOYEE_WRITE_COMPANY,
];

export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.OWNER]: ALL,
  [ROLES.ADMIN]: ADMIN,
  [ROLES.TEAM_MEMBER]: MEMBER,
  [ROLES.TEAM_LEADER]: LEADER,
  [ROLES.MANAGER]: MANAGER,
  [ROLES.HR]: HR,
});

export function permissionsForRole(role) {
  return ROLE_PERMISSIONS[role] ?? [];
}

export const ROLE_LABELS = Object.freeze({
  [ROLES.OWNER]: "Owner",
  [ROLES.ADMIN]: "Admin",
  [ROLES.TEAM_MEMBER]: "Employee",
  [ROLES.TEAM_LEADER]: "Team leader",
  [ROLES.MANAGER]: "Manager",
  [ROLES.HR]: "HR",
});

export function labelForRole(role) {
  return ROLE_LABELS[role] || String(role || "").replaceAll("_", " ");
}

// Roles HR can hand out when provisioning a new person. Owner, Admin, and
// Manager are granted by hand outside the create-employee form.
export const ASSIGNABLE_ROLES = Object.freeze([ROLES.TEAM_MEMBER, ROLES.TEAM_LEADER, ROLES.HR]);

export const HOLIDAY_KINDS = Object.freeze({
  FESTIVAL: "festival",
  OPTIONAL: "optional",
});

export const LEAVE_TYPES = Object.freeze({
  SICK: "sick",
  CASUAL: "casual",
  UNPAID: "unpaid",
});

export const LEAVE_TYPE_LIST = Object.freeze(Object.values(LEAVE_TYPES));

export const LEAVE_NOTICE_DAYS = Object.freeze({
  [LEAVE_TYPES.SICK]: 0,
  [LEAVE_TYPES.CASUAL]: 7,
  [LEAVE_TYPES.UNPAID]: 7,
});

export const LEAVE_TYPE_LABELS = Object.freeze({
  [LEAVE_TYPES.SICK]: "Sick leave",
  [LEAVE_TYPES.CASUAL]: "Casual leave",
  [LEAVE_TYPES.UNPAID]: "Unpaid leave",
});

export const LEAVE_ENTITLEMENTS = Object.freeze({
  [LEAVE_TYPES.SICK]: 12,
  [LEAVE_TYPES.CASUAL]: 12,
});

export const LEAVE_ENTITLEMENT_LIST = Object.freeze(Object.keys(LEAVE_ENTITLEMENTS));

export const DEMO_PASSWORD = "LocalDev!23";

// Payslip creation and running payment are restricted to these two people
// specifically (accounting), not the whole HR/Admin/Owner role — narrower
// than PERMISSIONS.PAYROLL_WRITE_COMPANY, which still governs read access.
export const PAYROLL_OPERATOR_EMPLOYEE_IDS = Object.freeze(["emp-chai", "emp-nagendra", "emp-priya", "emp-manoj"]);

// Full org chart. managerId builds the reporting tree; the leave approval
// chain follows managerId up to the top (Manoj, the owner).
// key is used on the login page for quick-fill demo accounts.
export const DEMO_ACCOUNTS = Object.freeze([
  // Owner (top)
  {
    key: "manoj",
    name: "Manoj",
    email: "manoj@thewebsitemakers.in",
    jobTitle: "CMO & Co-Founder",
    role: ROLES.OWNER,
    roleLabel: "Owner",
    initials: "M",
    userId: "user-manoj",
    employeeId: "emp-manoj",
    employeeNumber: "TWM-1001",
    managerId: null,
    departmentId: "dept-sales",
    teamId: "team-sales",
  },

  // Sales Team
  {
    key: "naveen",
    name: "Naveen",
    email: "naveen@twm.local",
    jobTitle: "Assistant Team Lead - Business Development",
    leaveApproverId: "emp-manoj",
    role: ROLES.TEAM_LEADER,
    roleLabel: "Team Lead - Sales",
    initials: "N",
    userId: "user-naveen",
    employeeId: "emp-naveen",
    employeeNumber: "TWM-1002",
    managerId: "emp-manoj",
    departmentId: "dept-sales",
    teamId: "team-sales",
  },
  {
    key: "aman",
    name: "Aman",
    email: "aman@twm.local",
    jobTitle: "Business Associate",
    leaveApproverId: "emp-manoj",
    role: ROLES.TEAM_MEMBER,
    roleLabel: "Business Associate",
    initials: "A",
    userId: "user-aman",
    employeeId: "emp-aman",
    employeeNumber: "TWM-1003",
    managerId: "emp-naveen",
    departmentId: "dept-sales",
    teamId: "team-sales",
  },
  {
    key: "suman",
    name: "Suman",
    email: "suman@twm.local",
    jobTitle: "Business Associate",
    leaveApproverId: "emp-manoj",
    role: ROLES.TEAM_MEMBER,
    roleLabel: "Business Associate",
    initials: "S",
    userId: "user-suman",
    employeeId: "emp-suman",
    employeeNumber: "TWM-1004",
    managerId: "emp-naveen",
    departmentId: "dept-sales",
    teamId: "team-sales",
  },
  {
    key: "shreya",
    name: "Shreya",
    email: "shreya@twm.local",
    jobTitle: "Business Associate",
    leaveApproverId: "emp-manoj",
    role: ROLES.TEAM_MEMBER,
    roleLabel: "Business Associate",
    initials: "S",
    userId: "user-shreya",
    employeeId: "emp-shreya",
    employeeNumber: "TWM-1005",
    managerId: "emp-naveen",
    departmentId: "dept-sales",
    teamId: "team-sales",
  },
  {
    key: "viney",
    name: "Viney",
    email: "viney@twm.local",
    jobTitle: "Business Associate",
    leaveApproverId: "emp-manoj",
    role: ROLES.TEAM_MEMBER,
    roleLabel: "Business Associate",
    initials: "V",
    userId: "user-viney",
    employeeId: "emp-viney",
    employeeNumber: "TWM-1006",
    managerId: "emp-naveen",
    departmentId: "dept-sales",
    teamId: "team-sales",
  },

  // Administration (admin access)
  {
    key: "prashanth",
    name: "Prashanth",
    email: "prashanth@twm.local",
    jobTitle: "B2B Director",
    role: ROLES.ADMIN,
    roleLabel: "Admin Access",
    initials: "P",
    userId: "user-prashanth",
    employeeId: "emp-prashanth",
    employeeNumber: "TWM-1007",
    managerId: "emp-manoj",
    departmentId: "dept-admin",
    teamId: "team-admin",
  },
  {
    key: "pushpa",
    name: "Pushpa",
    email: "pushpa@twm.local",
    jobTitle: "Vice President - Sales",
    role: ROLES.ADMIN,
    roleLabel: "Admin Access",
    initials: "P",
    userId: "user-pushpa",
    employeeId: "emp-pushpa",
    employeeNumber: "TWM-1008",
    managerId: "emp-manoj",
    departmentId: "dept-admin",
    teamId: "team-admin",
  },

  // HR Department (HR admin access)
  {
    key: "chai",
    name: "Chai",
    email: "chaitali@hiretick.in",
    jobTitle: "CEO - Hirect",
    role: ROLES.HR,
    roleLabel: "HR Admin Access",
    initials: "C",
    userId: "user-chai",
    employeeId: "emp-chai",
    employeeNumber: "TWM-1009",
    managerId: "emp-manoj",
    departmentId: "dept-hr",
    teamId: "team-hr",
  },
  {
    key: "moulika",
    name: "Moulika Kittur",
    email: "moulika@twm.local",
    jobTitle: "Senior HR",
    role: ROLES.HR,
    roleLabel: "HR Admin Access",
    initials: "MK",
    userId: "user-moulika",
    employeeId: "emp-moulika",
    employeeNumber: "TWM-1010",
    managerId: "emp-chai",
    departmentId: "dept-hr",
    teamId: "team-hr",
  },
  {
    key: "priya",
    name: "Priya",
    email: "priya@twm.local",
    jobTitle: "Peoples Manager",
    role: ROLES.HR,
    roleLabel: "HR Admin Access",
    initials: "P",
    userId: "user-priya",
    employeeId: "emp-priya",
    employeeNumber: "TWM-1011",
    managerId: "emp-chai",
    departmentId: "dept-hr",
    teamId: "team-hr",
  },
  {
    key: "nagendra",
    name: "Nagendra",
    email: "nagendra@twm.local",
    jobTitle: "Accountant",
    role: ROLES.HR,
    roleLabel: "HR Admin Access",
    initials: "N",
    userId: "user-nagendra",
    employeeId: "emp-nagendra",
    employeeNumber: "TWM-1012",
    managerId: "emp-chai",
    departmentId: "dept-hr",
    teamId: "team-hr",
  },

  // Web Development (team leads + developers)
  {
    key: "hari",
    name: "Hari",
    email: "hari@twm.local",
    jobTitle: "Team Lead - Web Development",
    role: ROLES.TEAM_LEADER,
    roleLabel: "Team Lead",
    initials: "H",
    userId: "user-hari",
    employeeId: "emp-hari",
    employeeNumber: "TWM-1013",
    managerId: "emp-manoj",
    departmentId: "dept-web",
    teamId: "team-web-hari",
  },
  {
    key: "charu",
    name: "Charu",
    email: "charu@twm.local",
    jobTitle: "Developer",
    role: ROLES.TEAM_MEMBER,
    roleLabel: "Developer",
    initials: "C",
    userId: "user-charu",
    employeeId: "emp-charu",
    employeeNumber: "TWM-1014",
    managerId: "emp-hari",
    departmentId: "dept-web",
    teamId: "team-web-hari",
  },
  {
    key: "sheesh",
    name: "Sheesh",
    email: "sheesh@twm.local",
    jobTitle: "Developer",
    role: ROLES.TEAM_MEMBER,
    roleLabel: "Developer",
    initials: "S",
    userId: "user-sheesh",
    employeeId: "emp-sheesh",
    employeeNumber: "TWM-1015",
    managerId: "emp-hari",
    departmentId: "dept-web",
    teamId: "team-web-hari",
  },
  {
    key: "manjappa",
    name: "Manjappa",
    email: "manjappa@twm.local",
    jobTitle: "Developer",
    role: ROLES.TEAM_MEMBER,
    roleLabel: "Developer",
    initials: "M",
    userId: "user-manjappa",
    employeeId: "emp-manjappa",
    employeeNumber: "TWM-1016",
    managerId: "emp-hari",
    departmentId: "dept-web",
    teamId: "team-web-hari",
  },
  {
    key: "gopi",
    name: "Gopi",
    email: "gopi@twm.local",
    jobTitle: "Team Lead - Web Development",
    role: ROLES.TEAM_LEADER,
    roleLabel: "Team Lead",
    initials: "G",
    userId: "user-gopi",
    employeeId: "emp-gopi",
    employeeNumber: "TWM-1017",
    managerId: "emp-manoj",
    departmentId: "dept-web",
    teamId: "team-web-gopi",
  },
  {
    key: "vamsi",
    name: "Vamsi",
    email: "vamsi@twm.local",
    jobTitle: "Developer",
    role: ROLES.TEAM_MEMBER,
    roleLabel: "Developer",
    initials: "V",
    userId: "user-vamsi",
    employeeId: "emp-vamsi",
    employeeNumber: "TWM-1018",
    managerId: "emp-gopi",
    departmentId: "dept-web",
    teamId: "team-web-gopi",
  },
  {
    key: "kamesh",
    name: "Kamesh",
    email: "kamesh@twm.local",
    jobTitle: "Developer",
    role: ROLES.TEAM_MEMBER,
    roleLabel: "Developer",
    initials: "K",
    userId: "user-kamesh",
    employeeId: "emp-kamesh",
    employeeNumber: "TWM-1019",
    managerId: "emp-gopi",
    departmentId: "dept-web",
    teamId: "team-web-gopi",
  },
  {
    key: "nandha",
    name: "Nandha",
    email: "nandha@twm.local",
    jobTitle: "Developer",
    role: ROLES.TEAM_MEMBER,
    roleLabel: "Developer",
    initials: "N",
    userId: "user-nandha",
    employeeId: "emp-nandha",
    employeeNumber: "TWM-1020",
    managerId: "emp-gopi",
    departmentId: "dept-web",
    teamId: "team-web-gopi",
  },
  {
    key: "prajwal",
    name: "Prajwal",
    email: "prajwal@twm.local",
    jobTitle: "Team Lead - Web Development",
    role: ROLES.TEAM_LEADER,
    roleLabel: "Team Lead",
    initials: "P",
    userId: "user-prajwal",
    employeeId: "emp-prajwal",
    employeeNumber: "TWM-1021",
    managerId: "emp-manoj",
    departmentId: "dept-web",
    teamId: "team-web-prajwal",
  },
  {
    key: "guru",
    name: "Guru",
    email: "guru@twm.local",
    jobTitle: "Developer",
    role: ROLES.TEAM_MEMBER,
    roleLabel: "Developer",
    initials: "G",
    userId: "user-guru",
    employeeId: "emp-guru",
    employeeNumber: "TWM-1022",
    managerId: "emp-prajwal",
    departmentId: "dept-web",
    teamId: "team-web-prajwal",
  },

  // Marketing & Media
  {
    key: "meghna",
    name: "Meghna",
    email: "meghna@twm.local",
    jobTitle: "Senior Social Media Manager",
    role: ROLES.TEAM_LEADER,
    roleLabel: "Team Lead - Marketing",
    initials: "M",
    userId: "user-meghna",
    employeeId: "emp-meghna",
    employeeNumber: "TWM-1023",
    managerId: "emp-manoj",
    departmentId: "dept-marketing",
    teamId: "team-marketing",
  },
  {
    key: "preetika",
    name: "Preetika",
    email: "preetika@twm.local",
    jobTitle: "Graphic Designer",
    role: ROLES.TEAM_MEMBER,
    roleLabel: "Graphic Designer",
    initials: "P",
    userId: "user-preetika",
    employeeId: "emp-preetika",
    employeeNumber: "TWM-1024",
    managerId: "emp-meghna",
    departmentId: "dept-marketing",
    teamId: "team-marketing",
  },
  {
    key: "krishne",
    name: "Krishne Kumar",
    email: "krishne@twm.local",
    jobTitle: "Graphic Designer",
    role: ROLES.TEAM_MEMBER,
    roleLabel: "Graphic Designer",
    initials: "KK",
    userId: "user-krishne",
    employeeId: "emp-krishne",
    employeeNumber: "TWM-1025",
    managerId: "emp-meghna",
    departmentId: "dept-marketing",
    teamId: "team-marketing",
  },
  {
    key: "afreen",
    name: "Afreen",
    email: "afreen@twm.local",
    jobTitle: "Content Manager",
    role: ROLES.TEAM_MEMBER,
    roleLabel: "Content Manager",
    initials: "A",
    userId: "user-afreen",
    employeeId: "emp-afreen",
    employeeNumber: "TWM-1026",
    managerId: "emp-meghna",
    departmentId: "dept-marketing",
    teamId: "team-marketing",
  },
  {
    key: "darshan",
    name: "Darshan",
    email: "darshan@twm.local",
    jobTitle: "Senior Video Editor",
    role: ROLES.TEAM_LEADER,
    roleLabel: "Team Lead - Media",
    initials: "D",
    userId: "user-darshan",
    employeeId: "emp-darshan",
    employeeNumber: "TWM-1027",
    managerId: "emp-manoj",
    departmentId: "dept-marketing",
    teamId: "team-marketing",
  },
  {
    key: "preeti",
    name: "Preeti",
    email: "preeti@twm.local",
    jobTitle: "Video Editing Intern",
    role: ROLES.TEAM_MEMBER,
    roleLabel: "Video Editing Intern",
    initials: "P",
    userId: "user-preeti",
    employeeId: "emp-preeti",
    employeeNumber: "TWM-1028",
    managerId: "emp-darshan",
    departmentId: "dept-marketing",
    teamId: "team-marketing",
  },
  {
    key: "nandha-video",
    name: "Nandha",
    email: "nandha.video@twm.local",
    jobTitle: "Video Editor",
    role: ROLES.TEAM_MEMBER,
    roleLabel: "Video Editor",
    initials: "N",
    userId: "user-nandha-video",
    employeeId: "emp-nandha-video",
    employeeNumber: "TWM-1029",
    managerId: "emp-darshan",
    departmentId: "dept-marketing",
    teamId: "team-marketing",
  },
]);

export function hasPermission(role, permission) {
  return permissionsForRole(role).includes(permission);
}
