import { chromium } from "playwright-core";
const browser = await chromium.launch({ executablePath: "/usr/bin/chromium", headless: true, args: ["--no-sandbox","--disable-gpu","--disable-dev-shm-usage"] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
await page.goto("http://localhost:5173/login", { waitUntil: "networkidle" });
await page.waitForTimeout(700);
await page.screenshot({ path: "login_demo.png" });
const tabs = await page.locator(".person-tab").allInnerTexts();
console.log("DEMO TAB COUNT:", tabs.length);
console.log(tabs.map(s => s.replace(/\n/g, " | ")).join("\n"));
await browser.close();
