import { chromium } from "playwright-core";
const BASE="http://localhost:5173";
const browser = await chromium.launch({ executablePath: "/usr/bin/chromium", headless: true, args: ["--no-sandbox","--disable-gpu","--disable-dev-shm-usage"] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto(BASE, { waitUntil: "networkidle" });
await page.fill('input[type="email"]', "chai@twm.local");
await page.fill('input[type="password"]', "LocalDev!23");
await page.click('button[type="submit"]');
await page.waitForSelector(".app-shell .sidebar", { timeout: 15000 });
await page.locator(".sidebar-link", { hasText: "Org Chart" }).click();
await page.waitForSelector(".org-layout", { timeout: 15000 });
await page.waitForTimeout(600);
await page.screenshot({ path: "green_active.png" });
await browser.close();
console.log("DONE");
